### ISSUE TITLE
Multiboard down because query.yahooapis.com is over

### ISSUE THREAD

**Issue by skapin** [sametmax/multiboards#3]
le service query.yahooapis.com est à la retraite donc plus de service donc.... plus de multiboard.

S'il vous plait multiboard c'est la vie, sauvez nous <3

**Comment by sametmax** [comment]
Va falloir réécrire l'équivalent à la main, et max semble avoir la flemme. Je vais essayer de le motiver.

Le 09/01/2019 à 16:49, SkapiN a écrit :

**Comment by skapin** [comment]
Si je trouve la passion je le ferai aussi. On se tient au courant. Le premier qui finit a gagné un kinder
